import { Noto_Sans } from 'next/font/google';
import "./globals.css";
import ThemeProvider from '../components/ThemeProvider'; // Adjust the path as necessary
import Navbar from '@/components/Navbar/Navbar';

const notoSans = Noto_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],  // Choose your desired font weights
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        <ThemeProvider>
            <Navbar/>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
